env:
    global:
      - CC_TEST_REPORTER_ID=50ca081fc23d15a5306f2428341b1a9fce4d9e612f538b537f91e005e17ede82
  language: node_js
  sudo: false
  node_js:
    - 10
    - 9
    - 8
    - 7
    - 6
  install:
    - npm install --prefix event-bus/
  before_script:
      - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
  script:
    - npm test --prefix event-bus/
  after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT